import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import NosServices from '@/components/NosServices'
import Portfolio from '@/components/Portfolio'
import QuiSommesNous from '@/components/QuiSommesNous'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>ANIMA Technologies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <QuiSommesNous />
      <NosServices />
      <Portfolio />
      <Footer />
    </>
  )
}
